name: Generate Site with Maven

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: adopt
          cache: maven

      - name: Build Docs with Maven
        run: mvn site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: target/site/ # The folder the action should deploy.
          ssh-key: ${{ secrets.DEPLOY_KEY }}
